baseURL = "https://sashmit.com"
title = "Sashmit Bhaduri"
theme = "hugo-theme-zzo"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false

summaryLength = 70

copyright = "&copy;{year}, Sashmit Bhaduri All Rights Reserved"
timeout = 10000
enableEmoji = true
paginate = 15
rssLimit = 500

enableGitInfo = true
googleAnalytics = "G-W653NMQV9S"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
